import Head from "next/head";
import { Poppins } from "@next/font/google";
import Header from "@/components/Header/Header";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

interface Props {
  children: JSX.Element;
}

const BaseLayout = ({ children }: Props) => {
  return (
    <>
      <Head>
        <title>Fashion</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className={`layout relative ${poppins.variable} w-full min-h-[100vh] flex flex-col`}
      >
        <Header />

        <main className="font-poppins w-full flex-1">{children}</main>
      </div>
    </>
  );
};

export default BaseLayout;
